apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-app-deployment
  labels:
    app: storage-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: storage-app
  template:
    metadata:
      labels:
        app: storage-app
    spec:
      containers:
      - name: storage-app
        image: mm1995/react-app
        ports:
        - containerPort: 80