apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-app-container
    tier: frondend
  name: react-app
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: react-app
  sessionAffinity: None
  type: ClusterIP


  