 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: myapp
     part: front
   name: frontapp
   namespace: default
 spec:
   ports:
   - port: 80
     protocol: TCP
     targetPort: 80 # Port on the pod with 'back' application
   selector:
     app: myapp
     part: front
   type: NodePort