apiVersion: v1
kind: Service
metadata:
  name: react
  namespace: default
  labels:
    app: react
  annotations:
    service.beta.kubernetes.io/aws-node-port-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: react
  type: NodePort