apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: storage-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mary.thecodingground.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontapp
          servicePort:  3000
      - path: /
        backend:
          serviceName: backapp
          servicePort:   8080