apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: storage-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mary.thecodingground.com
    http:
      paths:
      - path: /
        backend:
          serviceName: react
          servicePort: 8080
      - path: /
        backend:
          serviceName: node
          servicePort:  3001