apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
  labels:
    app: express-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: mm1995/express-app
        ports:
        - containerPort: 80
        env:
        database-name: store_prodcuts
        database-user: postgres
        database-password: TCGPC1
        connect-postgres: postgres://postgres:TCGPC1@localhost:5432/store_products 