apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-kubernetes
spec:
  selector:
    matchLabels:
      app: app-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: node-kubernetes
    spec:
      containers:
      - name: app-kubernetes
        image: docker.io/bricerisingslalom/app-k8s:latest
        ports:
        - containerPort: 
     