# kind: Service
# apiVersion: v1
# metadata:
#   name: hello-kubernetes
# spec:
#   type: NodePort
#   selector:
#     app: hello-kubernetes
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80

kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres-container
    tier: backend
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432