apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: default
  labels:
    app: node
  annotations:
    service.beta.kubernetes.io/aws-node-port-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 80
  selector:
    app: node
  type: NodePort