
kind: Service
apiVersion: v1
metadata:
  name: react-app
spec:
  selector:
    app: react-app-container
    tier: frondend
  ports:
  - name: react-app
    protocol: TCP
    port: 5432
    targetPort: 5432